# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: journaling to clear the space
author: ferunande
email: ferunande@gureito.info
description: >- # this means to ignore newlines until "baseurl:"
  semi-(ir)regular updates on (searching for) myself.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gureito
github_username:  gureito

show_excerpts: true
permalink: :categories/:year-:month-:day-:title:output_ext
minima:
  date_format: "%Y/%m/%d"
# Build settings
#markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
- editors
- todo.txt
- Gemfile
- Gemfile.lock
- CNAME
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
